### ISSUE TITLE
试用了一下，感觉不错。

### ISSUE THREAD

**Issue by lizenghui** [XMD0718/gfwlist#1]
赞！

**Comment by lizenghui** [comment]
发现个问题pixel手机用这个  wifi会显示无法连接到互联网  不知道是少了哪个域名。gstatic.com吗？

**Comment by XMD0718** [comment]
> 发现一个问题像素手机用这个wifi会显示无法连接到互联网不知道是少了哪个域名。gstatic.com吗？

请问具体是哪个APP或者访问了哪个网站出现了问题？最新版本已添加gstatic.com，https://raw.githubusercontent.com/XMD0718/gfwlist/main/gfwlist.txt，请使用此URL进行更新

**Comment by lizenghui** [comment]
> > 发现一个问题像素手机用这个wifi会显示无法连接到互联网不知道是少了哪个域名。gstatic.com吗？
> 
> 请问具体是哪个APP或者访问了哪个网站出现了问题？
> 最新版本已添加gstatic.com，
> [请使用此URL进行更新](https://raw.githubusercontent.com/XMD0718/gfwlist/main/gfwlist.txt)

不是APP和网站    我的是google  pixel手机  原生android   
![image](https://user-images.githubusercontent.com/13620083/111464146-61f2ae00-875b-11eb-90ea-852dca9107f1.png)
手机连上wifi显示这样。

**Comment by XMD0718** [comment]
是挂了代理才显示的？

**Comment by lizenghui** [comment]
> 这里提供一个解决方法，ADB连接手机，使用指令
> `adb shell settings put global captive_portal_https_url https://www.google.cn/generate_204`
> 若平时正常，只有在使用我维护的GFW列表挂代理使用时才这样，可以进行下一步讨论

现在貌似不用这个方法了。正常连上没有FQ的wifi也显示正常，会不会是多了一些域名？
我用https://github.com/gfwlist/gfwlist这个是正常的。但是这个更新慢有好多像duyaoss.com这种还要自己配

**Comment by XMD0718** [comment]
这个只能去开启服务端日志，然后抓日志去找到问题所在，几千个域名，没办法排查

**Comment by lizenghui** [comment]
> 这个只能去开启服务端日志，然后抓日志去找到问题所在，几千个域名，没办法排查

好的  我再试试。
